name: My Jobs

on: [push]

jobs:
  build:
    runs-on: [ self-hosted, currency-exchange ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
      - name: Set up maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '4.0.0-rc-1'
      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Build with Maven
        run: mvn -B -U -DskipTests clean package

  test:
    runs-on: [ self-hosted, currency-exchange ]
    needs: build
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
      - name : Set up maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '4.0.0-rc-1'
      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Run Spring Boot tests
        run: mvn -B -U test

  build_push_image:
    needs: build
    runs-on: [self-hosted, currency-exchange]
    steps:
      - uses: actions/checkout@v5
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: letrung1998vn/currency-exchange:latest
      - name: Deploy to remote Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          script: |
            docker pull currency-exchange:latest
            docker stop currency-exchange-app || true  
            docker rm currency-exchange-app || true    
            docker run -d --name currency-exchange-app -p 8080:8080 currency-exchange:latest